apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: googleservice
  name: googleservice-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleservice
  strategy: {}
  template:
    metadata:
      labels:
        app: googleservice
    spec:
      containers:
        - image: replace
          name: googleservice-container
---
apiVersion: v1
kind: Service
metadata:
  labels: googleservice
  name: googleservice-srv
spec:
  selector:
    app: googleservice
  ports:
    - name: googleservice
      protocol: TCP
      port: 3000
      targetPort: 3000